Revert "Only extract zipapex once for linux-bionic-zipapex tests"
Somehow an exception in the main thread doesn't cause testrunner.py
to exit non-zero.

This reverts commit 912cee8ab1260c5022ddb4862620d6ed17658de7.

Test: None

Reason for revert: Python version incompatibility

['/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py', '--run-test-option=--bionic', '--runtime-zipapex=/usr/local/google/buildbot/src/googleplex-android/master-art-host/out/soong/host/linux_bionic-x86/apex/com.android.runtime.host.zipapex', '--host', '--64', '--no-build-dependencies', '--host', '--dex2oat-jobs', '4', '--verbose']
Concurrency: 40
4150/4150 (100%) tests passed.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 508, in run_tests
    with handle_zipapex(zipapex_loc) as zipapex_opt:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 531, in handle_zipapex
    subprocess.run(["unzip", "-qq", ziploc, "apex_payload.zip", "-d", tmpdir]).check_returncode()
AttributeError: 'module' object has no attribute 'run'

Change-Id: I33a87fc2d96b250e30e3e08c60e9197daa11e049