Ignore libcore.java.lang.ThreadTest failures on device.
Since https://android-review.googlesource.com/#/c/209427
has been merged, libcore.java.lang.ThreadTest tests are
failing with this error on ARM64:

  java.lang.UnsatisfiedLinkError: dlopen failed: library "libnativehelper_compat_libc++.so" not found
      at java.lang.Runtime.loadLibrary0(Runtime.java:977)
      at java.lang.System.loadLibrary(System.java:1628)
      at libcore.java.lang.ThreadTest.<clinit>(ThreadTest.java:26)

Ignore those failures for now to make the build turn green
again, while we investigate.

Bug: 28082914
Change-Id: Ia8c3c776c99aace06701479d1440c828d39cbec3