Add a command to test Pre-reboot Dexopt.
Example output on a success:

Success

Example output on a dexopt_chroot_setup crash:

Failure
java.lang.RuntimeException: java.lang.AssertionError: Unexpected exception
Caused by: java.lang.AssertionError: Unexpected exception
	at com.android.server.art.prereboot.PreRebootDriver.test(PreRebootDriver.java:118)
	at com.android.server.art.PreRebootDexoptJob.lambda$test$4(PreRebootDexoptJob.java:306)
	at com.android.server.art.PreRebootDexoptJob.$r8$lambda$vA3mIzCbYJKwqMfUmi5afiGfDY0(PreRebootDexoptJob.java:0)
	at com.android.server.art.PreRebootDexoptJob$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1780)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at com.android.server.art.IDexoptChrootSetup$Stub$Proxy.init(IDexoptChrootSetup.java:154)
	at com.android.server.art.prereboot.PreRebootDriver.setUp(PreRebootDriver.java:127)
	at com.android.server.art.prereboot.PreRebootDriver.test(PreRebootDriver.java:113)
	... 7 more

Bug: 311377497
Test: adb shell pm art pr-dexopt-job --test
(cherry picked from https://android-review.googlesource.com/q/commit:ca83e1a0008e1eee3e5b6999a8fb643e41d556b6)
Merged-In: Ie72dd279b0177b7f0500cfb79db6f65544327959
Change-Id: Ie72dd279b0177b7f0500cfb79db6f65544327959