Revert "Implement LockSupport.park with a futex"
This reverts commit 5e1a75c1d12ea47bdc0f73d378b5fa25326829f4.

Reason for revert: This CL unfortunately breaks:
sdk_gphone_x86-sdk_addon_mac
sdk_mac

Following error:
art/runtime/thread.cc:370:4: warning: "LockSupport.park/unpark implemented as noops without FUTEX support." [-W#warnings]
#warning "LockSupport.park/unpark implemented as noops without FUTEX support."
^
art/runtime/thread.cc:295:24: error: unused parameter 'is_absolute' [-Werror,-Wunused-parameter]
void Thread::Park(bool is_absolute, int64_t time) {
^
art/runtime/thread.cc:295:45: error: unused parameter 'time' [-Werror,-Wunused-parameter]
void Thread::Park(bool is_absolute, int64_t time) {
^
1 warning and 2 errors generated.

Change-Id: Iae41cce7cd5fc38f605173519931491a019f7c80