adbconnection: Reject subsequent debugger
Problem: After a JDWP client has been accepted, adbconnection does not
poll(3) adbd for incoming data. This means if a client is connected, any
subsequent client attempting to connect will hang (we never reply or
close).

There is actually a provision for this case on line 625 to reject a
second debugger but this branch is never taken since we don't request
poll(3) while we have a client.

Solution: Change poll(3) request to always let us know of an incoming
JDWP client. This let's us close(3) it and fail instead of hanging. Note
this was the behavior up to API 28 (Dalv(CR) implementation).

Fixes: 309142640
Test: TBD

For now, testing is done manually.

```
$ adb forward tcp:6666 jdwp:`adb shell pidof com.example.helloworld`
$ jdb -attach localhost:6666 &
$ jdb -attach localhost:6666
java.io.IOException: handshake failed - connection prematurally closed
```

Change-Id: I0f35bc8751acfc9740b7fd362685e96d31d03570