Ignore comment lines in proguard mapping.
Comment lines are now being generated by R8 in the proguard mapping.
Update the proguard mapping parser to handle those. Fixes the ahat test
failure:

1) diffMatchedHeap(com.android.ahat.DiffTest)
java.io.IOException: Unable to load proguard map
  at com.android.ahat.TestDump.load(TestDump.java:116)
  at com.android.ahat.TestDump.getTestDump(TestDump.java:269)
  at com.android.ahat.TestDump.getTestDump(TestDump.java:241)
  at com.android.ahat.DiffTest.diffMatchedHeap(DiffTest.java:32)
  ...
Caused by: java.text.ParseException: Error parsing class line: '# compiler: R8'
  at com.android.ahat.proguard.ProguardMap.parseException(ProguardMap.java:142)
  at com.android.ahat.proguard.ProguardMap.readFromReader(ProguardMap.java:191)
  at com.android.ahat.TestDump.load(TestDump.java:114)
  ... 33 more

Change-Id: I70c9deb414086f454a1f3fefd3bace5b78953b44
Test: m ahat-test